### ISSUE TITLE
ng-2 dnd not installing

### ISSUE THREAD

**Issue by olufemioyedepo** [DataExperts/dexih-ngx-table#1]
when i run npm install ng2-dnd --save, it fails to install.

**Comment by gary-holland** [comment]
I can't help you on this as it is an external library used by the table for drag/drop.  You could try for some help [here](https://github.com/akserg/ng2-dnd), however I'd suggest providing a little more info when doing so, such as the actual error message, and details of your environment.

**Comment by olufemioyedepo** [comment]
this is what i get after running **npm install ng2-dnd --save**

npm WARN codelyzer@3.2.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must
 install peer dependencies yourself.
npm WARN codelyzer@3.2.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must ins
tall peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, rename 'C:\Angular2\concepts\concept
s\node_modules\.staging\fsevents-a908a0ca\node_modules\ajv' -> 'C:\Angular2\concepts\concepts\node_modules\.staging\ajv-13d
04b68'

npm ERR! path C:\Angular2\concepts\concepts\node_modules\ng2-dnd
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Angular2\concepts\concepts\node_modules\ng2-dnd' -> 'C:\Angul
ar2\concepts\concepts\node_modules\.ng2-dnd.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JS\AppData\Roaming\npm-cache\_logs\2018-02-12T10_25_11_535Z-debug.log
