### ISSUE TITLE
Font Awesome Icons Not Appearing

### ISSUE THREAD

**Issue by brentspector** [DataExperts/dexih-ngx-table#2]
If using Angular 5 and Font Awesome 5, you need to do the following to get the icons to appear.
-Import something from the free-solid library as such and place it in the TS file of the component containing dexih-table
import { faChevronLeft } from '@fortawesome/fontawesome-free-solid';

-Generate the fontawesome library by placing the following code in the ngOnInit of the same TS file.
fontawesome.library.add(faChevronLeft);

Ideally this should be covered by the dexih-table tool.

**Comment by gary-holland** [comment]
Thanks for raising this sus.e

If you link the font awesome CDN into your project, you should be able to see icons without any imports.  Here is an example: http://plnkr.co/edit/G3RNCVGMXhodH7Ap 

If you're loading these icons as part of your build, you will need to do the imports as noted above to have these included.  The dexih-table tool references these icon in the data fields which are only known at runtime, so I'm not sure how the library would accomodate this. 

Let me know if you have any ideas, or if you're able to replicate through a plnkr.

Thanks,
Gary

**Comment by brentspector** [comment]
I didn't add the CDN to my project but it appears 0.1.39 now displays icons. Consider the issue closed.
