### ISSUE TITLE
Sort Icons Don't Appear

### ISSUE THREAD

**Issue by brentspector** [DataExperts/dexih-ngx-table#3]
-Font Awesome 5 changed it to sort-amount-up (previously sort-amount-asc) and sort-amount-down (previously sort-amount-desc)

This should be fixed in the code.

**Comment by gary-holland** [comment]
Thanks for letting me know.  I've updated the classes with both font awesome 4.7/5.0 icons (note the export icon was also different).  They seem to be coexisting ok.  Check version 0.1.38-beta.

**Comment by brentspector** [comment]
Icons now display correctly. http://prntscr.com/jbrwyx

Old issue of duplicated icons still exists, but I feel that's probably my project.
