### ISSUE TITLE
Filtering After Sort Gives Wrong Records

### ISSUE THREAD

**Issue by brentspector** [DataExperts/dexih-ngx-table#4]
Data Before Filtering: http://prntscr.com/j8gxus
Data After Filtering: http://prntscr.com/j8gxx3

-this.data and _this.tableItems are not order synced. Thus looping through this.data gives the wrong index for the related _this.tableItems record. Need to loop through this.tableItems and get the related this.data record based on the index stored in the tableItem.

-Additionally, "N", "U" and "L" always return all records. This is due to fetchFromObject returning null and then being converted to "null"

-Fix by changing updateFilter as follows
if (this.filterString) {
                const filter_1 = this.filterString.toLowerCase();
                this.tableItems.forEach(function (row, index) {
                    var isMatch = false;
                    const dataRow = _this.data[_this.columnOperations.fetchFromObject(row, 'index')];
                    _this.currentColumns.forEach(function (column) {
                        const columnNameValue = _this.columnOperations.fetchFromObject(dataRow, column.name);
                        const columnFooterValue = _this.columnOperations.fetchFromObject(dataRow, column.footer);
                        if ((columnNameValue != null && String(columnNameValue).toLowerCase().includes(filter_1)) ||
                            (columnFooterValue != null && String(columnFooterValue).toLowerCase().includes(filter_1)) ) {
                            isMatch = true;
                        }
                    });
                    
                    _this.tableItems[index].isFiltered = !isMatch;
                });
            }

**Comment by gary-holland** [comment]
Thanks for raising this and providing some analysis.  I was able to replicate and I've implemented the changes (pretty much as you suggested) and performed some quick tests.  It seems to be working now (update to the 0.1.38-beta).  Please let me know if this resolves, and I'll close the issue.

**Comment by brentspector** [comment]
Filtering after sort works. Searching for "N", "U", or "L" only returns records with those letters. You can close this issue.
