### ISSUE TITLE
Not Compatible With Ngx-md 6.0

### ISSUE THREAD

**Issue by brentspector** [DataExperts/dexih-ngx-table#5]
While attempting to upgrade to Angular 6, I had this error come up. It does not appear to be my project configuration as a fresh Angular 6 install gives the same error when using dexih-ngx-table. Ngx-md 6.0 is needed for Angular 6 as the RXJS 6 dependency made breaking changes in file structure.

dexih-ngx-table.umd.js:514 Uncaught TypeError: Cannot read property 'forRoot' of undefined
    at dexih-ngx-table.umd.js:514
    at dexih-ngx-table.umd.js:526
    at dexih-ngx-table.umd.js:2
    at Object../node_modules/dexih-ngx-table/dexih-ngx-table.umd.js (dexih-ngx-table.umd.js:5)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/app.module.ts (app.component.ts:8)
    at __webpack_require__ (bootstrap:76)
    at Object../src/main.ts (environment.ts:15)
    at __webpack_require__ (bootstrap:76)
    at Object.0 (main.ts:12)

**Comment by gary-holland** [comment]
Thanks for letting me know.  

I've replicated your issue and fixed (just a module name change), however there is an additional problem with the ng2-dnd library compatibility which is breaking the build, so I'll need to look into that before committing change.  Hopefully next day or two.

**Comment by gary-holland** [comment]
I've updated this now (version 3).  Let me know if this get's it working for you.

Cheers,
Gary

**Comment by brentspector** [comment]
Yes this looks like it works. Thanks!
